### ISSUE TITLE
can you help me i use this  react-native-stories  in expo  but have bug 

### ISSUE THREAD

**Issue by ahmedzaki72** [Amit-khatkar/react-native-insta-stories#3]
pls can you help me fixed this bug i use this stories and is very good work  but i have bug i will create video show you this bug when open story 2  the story open 1 and go 2 and if video in story  1 he work 
and i'm open story 2 how to fixed this bug pls help me @Amit-khatkar @trinadhkoya

**Comment by iamitkhatkar** [comment]
hi @ahmedzaki72 , please upload that video and I'll fix that for you :)

**Comment by ahmedzaki72** [comment]
github not support upload video pls send me mail and i will  send video or whatsapp number @Amit-khatkar

**Comment by ahmedzaki72** [comment]
this is video bro pls fixed bug  .
note : i use expo video docs 
link : https://snaportsa65c698c9ba8449bb434a400b06f40f5-healiot.s3-eu-west-1.amazonaws.com/public/WhatsApp+Video+2019-11-18+at+4.59.20+PM.mp4 
@Amit-khatkar @trinadhkoya

**Comment by ahmedzaki72** [comment]
Hi bro I send you your video pls help me fixed this bug and I send code you or push code stories for expo in this repository @Amit-khatkar

**Comment by ahmedzaki72** [comment]
hi bro i fixed this bug add me in this repository and i will add version with expo code @Amit-khatkar 
@trinadhkoya

**Comment by iamitkhatkar** [comment]
hey @ahmedzaki72  Please fork the repo and do the changes. after that create a PR, I'll merge it
